{
 "title": "NSO Process Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CPU Utilization - Packages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nso_proc_cpu{name=\"ncs\"} "
    },
    {
     "expr": "nso_proc_cpu{name=\"java-vm\"}"
    },
    { "expr": "nso_proc_cpu_pkg" }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nso_proc_cpu" }
   ]
  },
  {
   "title": "Memory Usage - Packages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "nso_proc_mem{name=\"ncs\"} "
    },
    {
     "expr": "nso_proc_mem{name=\"java-vm\"}"
    },
    { "expr": "nso_proc_mem_pkg" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "nso_proc_mem" }
   ]
  },
  {
   "title": "Connections - Packages",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nso_proc_conn{name=\"ncs\"} "
    },
    {
     "expr": "nso_proc_conn{name=\"java-vm\"}"
    },
    { "expr": "nso_proc_conn_pkg" }
   ]
  },
  {
   "title": "Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nso_proc_conn" }
   ]
  }
 ]
}