{
 "title": "Log files",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total count log lines",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "logs_lines_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Critial log messages per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(logs_severity_total{severity=\"CRIT\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total logs lines per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    { "expr": "rate(logs_lines_total[1m])", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Error log messages per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(logs_severity_total{severity=\"ERROR\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Log lines per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(mtail_log_lines_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Warning log messages per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(logs_severity_total{severity=\"WARNING\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Info log messages per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "rate(logs_severity_total{severity=\"INFO\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Debug log messages per minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(logs_severity_total{severity=\"DEBUG\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}