{
 "title": "NSO Observability",
 "description": "Metrics on Cisco NSO",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "jaeger_base_url", "label": "jaeger_base_url", "query": "http://127.0.0.1:16686/" }
  ]
 },
 "panels": [
  {
   "title": "transactions",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "transaction-lock",
     "query": "SELECT count(\"duration\") FROM \"span\" WHERE (\"name\" = 'applying transaction') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "queue-length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "t-lock",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "limit": "1",
     "measurement": "transaction-lock",
     "query": "SELECT \"held\" FROM \"transaction-lock\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "held" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "queue length",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "transaction-lock",
     "query": "SELECT mean(\"queue-length\") FROM \"transaction-lock\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "queue-length" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Transactions",
   "type": "graph",
   "description": "Transaction throughput",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Number of transactions",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "span",
     "query": "SELECT count(\"duration\") FROM \"span\" WHERE (\"name\" = 'applying transaction') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "create" }
     ]
    },
    {
     "alias": "Transaction length",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "span",
     "query": "SELECT mean(\"duration\") FROM \"span\" WHERE (\"name\" = 'applying transaction') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "create" }
     ]
    }
   ]
  },
  {
   "title": "Longest transactions",
   "type": "table",
   "description": "This is a top list of the longest transactions for the given time period. Use it to identify things that might be slow.\n\nA long transaction in itself might not be a bad thing since transactions can essentially be idle and not block other transactions. However, if any lock is taken, the transaction should try to finish as soon as possible.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(\"duration\", 100), trace_id, tid FROM \"span\" WHERE \"name\" = 'applying transaction' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction lock & queue length",
   "type": "graph",
   "description": "The shaded red background shows when the transaction-lock is held (but will tend to overestimate due to time aggregation, zoom in for a better look!). The yellow line is a moving average of the time the transaction-lock is held.\nFinally, the blue line shows the length of the queue to the transaction-lock, i.e. how many transactions are trying to acquire the transaction-lock.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "transaction-lock held" }
   ],
   "targets": [
    {
     "alias": "held",
     "measurement": "transaction-lock",
     "query": "SELECT max(\"held\") FROM \"transaction-lock\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "held" ], "type": "field" }
      ]
     ]
    },
    {
     "alias": "queue length",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "transaction-lock",
     "query": "SELECT mean(\"queue-length\") FROM \"transaction-lock\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "queue-length" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "lock",
     "measurement": "transaction-lock",
     "query": "SELECT moving_average(mean(\"held\"),10) FROM \"transaction-lock\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "held" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transaction duration",
   "type": "graph",
   "description": "A histogram of total transaction duration. Notice this includes parts outside of the transaction-lock.\n\nX-axis shows buckets of transaction duration in seconds.\nY-axis is the number of transactions in that bucket.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "transaction duration",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "transaction",
     "query": "SELECT max(\"transaction\")/1000000 FROM \"transaction\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "transaction" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "System",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "HA synchronization time",
     "type": "graph",
     "description": "Time spent synchronizing changes in a HA group.",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "configuration data",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "span",
       "query": "SELECT max(\"duration\") FROM \"span\" WHERE (\"name\" = 'create') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        {
         "key": "name",
         "operator": "=",
         "value": "distributing configuration data changeset to all (available) slaves"
        }
       ]
      },
      {
       "alias": "operational data",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "span",
       "query": "SELECT max(\"duration\") FROM \"span\" WHERE (\"name\" = 'create') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        {
         "key": "name",
         "operator": "=",
         "value": "distributing operational data changeset to all (available) slaves"
        }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Transaction details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Waiting for transaction lock",
     "type": "graph",
     "description": "The time to grab the transaction lock plotted against the transaction lock queue length.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "alias": "grabbing transaction lock",
       "measurement": "span",
       "query": "SELECT mean(\"duration\") FROM \"span\" WHERE (\"name\" = 'grabbing transaction lock') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "grabbing transaction lock" }
       ]
      },
      {
       "alias": "max grabbing transaction lock",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT max(\"duration\") FROM \"span\" WHERE (\"name\" = 'grabbing transaction lock') AND $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "transaction lock queue length",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT mean(\"queue-length\") FROM \"transaction-lock\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Longest wait for transaction lock",
     "type": "table",
     "description": "This is a top list of the transactions that had to wait the longest in queue to acquire the transaction lock.\n\nThis list is hardly actionable in the sense that you wouldn't start looking at these transactions for tuning performance. Instead, these transactions are those that have waited the longest for other transactions to finish.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT top(\"duration\", 100), trace_id, tid FROM \"span\" WHERE \"name\" = 'grabbing transaction lock' AND $timeFilter",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Transaction phases",
     "type": "graph",
     "description": "The transaction phases as a percentage of the total transaction time.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "validate",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "transaction",
       "query": "SELECT (max(\"validate\")/max(\"transaction\"))*100 FROM \"transaction\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "write-start",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT (max(\"write-start\")/max(\"transaction\"))*100 FROM \"transaction\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "prepare",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT (max(\"prepare\")/max(\"transaction\"))*100 FROM \"transaction\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "commit",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "query": "SELECT (max(\"commit\")/max(\"transaction\"))*100 FROM \"transaction\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Data validation",
     "type": "heatmap",
     "description": "Shows the time it takes to validate the data as a percentage of the total time the transaction lock is held.\n\nA high percentage could indicate problematic XPath constraints that could be optimized.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "targets": [
      {
       "alias": "rollback percentage",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "span",
       "query": "SELECT ((max(\"pre validate\")+max(\"run validation over the changeset\")+max(\"run dependency-triggered validation\"))/max(\"holding transaction lock\"))*100\nFROM transaction\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "creating rollback file" }
       ]
      }
     ]
    },
    {
     "title": "Rollback file creation",
     "type": "heatmap",
     "description": "Shows the time it takes to create the rollback file as a percentage of the total time the transaction lock is held.\n\nIt is possible to disable rollback files for NSO if not needed for the deployment and can yield a non-negligible performance improvement. For very short transactions the rollback file creation can take a unproportionately large percentage and might be somewhat misleading.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "targets": [
      {
       "alias": "rollback percentage",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "span",
       "query": "SELECT (max(\"creating rollback file\")/max(\"holding transaction lock\"))*100\nFROM transaction\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "creating rollback file" }
       ]
      }
     ]
    },
    {
     "title": "Rollback file creation",
     "type": "graph",
     "description": "Time spent creating the rollback file for a transaction \n\nAlso compared ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "alias": "rollback percentage",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "span",
       "query": "SELECT (max(\"creating rollback file\")/max(\"holding transaction lock\"))*100\nFROM transaction\nWHERE $timeFilter\nGROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "creating rollback file" }
       ]
      },
      {
       "alias": "holding transaction lock",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "span",
       "query": "SELECT max(\"holding transaction lock\") FROM \"transaction\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "holding transaction lock" }
       ]
      },
      {
       "alias": "creating rollback file",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "span",
       "query": "SELECT max(\"creating rollback file\") FROM \"transaction\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "duration" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "name", "operator": "=", "value": "creating rollback file" }
       ]
      }
     ]
    }
   ]
  },
  { "title": "Services", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "service modifications",
   "type": "graph",
   "description": "This panel includes the create() callback of classic services as well as the \"run service\" span of nano-services.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "service create",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "span",
     "query": "SELECT mean(\"duration\") FROM \"span\" WHERE \"name\" = 'create' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "create" }
     ]
    },
    {
     "alias": "service create max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "span",
     "query": "SELECT max(\"duration\") FROM \"span\" WHERE \"name\" = 'create' AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "create" }
     ]
    },
    {
     "alias": "nano-service",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "span",
     "query": "SELECT mean(\"duration\") FROM \"span\" WHERE \"name\" = 'run service' AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "create" }
     ]
    },
    {
     "alias": "nano-service max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "span",
     "query": "SELECT max(\"duration\") FROM \"span\" WHERE \"name\" = 'run service' AND $timeFilter GROUP BY time($__interval) ",
     "select": [
      [
       { "params": [ "duration" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "create" }
     ]
    }
   ]
  },
  {
   "title": "Mean time in create per service type",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$tag_service_type",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "service_type" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT mean(\"duration\") AS \"duration\" FROM \"span\" WHERE (\"name\"='create' OR \"name\" = 'run service') AND $timeFilter GROUP BY \"service_type\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Longest service spans",
   "type": "table",
   "description": "This is a top list of the longest service create spans for the given time period. Use it to identify your slowest services and speed them up!",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(\"duration\", 100), service, trace_id FROM \"span\" WHERE (\"name\" = 'create' OR \"name\" = 'run service') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "Devices", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Device locks",
   "type": "graph",
   "description": "Shows device locks held over time",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short", "label": "device lock held" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device-lock",
     "query": "SELECT mean(\"held\") FROM \"device-lock\" WHERE $timeFilter GROUP BY \"device\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "held" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Longest get-trans-id",
   "type": "table",
   "description": "This is a top list of the longest get-trans-id operations for the given time period. Use it to identify things that might be slow.\n\nA long transaction in itself might not be a bad thing since transactions can essentially be idle and not block other transactions. However, if any lock is taken, the transaction should try to finish as soon as possible.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(\"duration\", 100), trace_id, tid FROM \"span\" WHERE \"name\" = 'get-trans-id' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Longest device connection",
   "type": "table",
   "description": "This is a top list of the longest get-trans-id operations for the given time period. Use it to identify things that might be slow.\n\nA long transaction in itself might not be a bad thing since transactions can essentially be idle and not block other transactions. However, if any lock is taken, the transaction should try to finish as soon as possible.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(\"duration\", 100), trace_id, tid FROM \"span\" WHERE \"name\" = 'connect' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Longest sync-from",
   "type": "table",
   "description": "This is a top list of the longest sync-from operations for the given time period.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT top(\"duration\", 100), trace_id, tid FROM \"span\" WHERE \"name\" = 'sync-from' AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Concurrent device operations",
   "type": "graph",
   "description": "Shows some device related operations that happen concurrently.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short", "label": "device lock held" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "device-lock",
     "query": "SELECT mean(\"count\") FROM \"span-count\" WHERE (\"name\" = 'connect' OR \"name\" = 'pre validate' OR \"name\" = 'show' OR \"name\" = 'sync-from' OR \"name\" = 'taking device lock' OR \"name\" = 'ned-migrate')  AND $timeFilter GROUP BY \"name\", time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "held" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}