{
 "title": "NSO Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Transactions Running",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysadmin_gauge_transaction_running",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Device Total",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sysadmin_gauge_device_total" }
   ]
  },
  {
   "title": "Commit Queue Length",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysadmin_gauge_commit_queue_item_executing"
    },
    {
     "expr": "sysadmin_gauge_commit_queue_item_waiting"
    },
    {
     "expr": "sysadmin_gauge_commit_queue_item_locked"
    },
    {
     "expr": "sysadmin_gauge_commit_queue_item"
    }
   ]
  },
  {
   "title": "Sessions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysadmin_gauge_session_cli_open"
    },
    { "expr": "sysadmin_gauge_session_open" },
    {
     "expr": "sysadmin_gauge_session_restconf_open"
    }
   ]
  },
  {
   "title": "Sync-From",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysadmin_counter_device_sync_from_created"
    },
    {
     "expr": "sysadmin_counter_device_sync_from_total"
    }
   ]
  },
  {
   "title": "Compactions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sysadmin_counter_cdb_compactions_created"
    },
    {
     "expr": "sysadmin_counter_cdb_compactions_total"
    }
   ]
  }
 ]
}