{
 "title": "NSO Process Monitor",
 "templating": {
  "list": [
   {
    "name": "hostname",
    "label": "hostname",
    "query": "SHOW TAG VALUES WITH KEY = \"hostname\" WHERE \"host_hostname\" = '${host_hostname:text}'"
   },
   {
    "name": "host_hostname",
    "label": "host_hostname",
    "query": "SHOW TAG VALUES WITH KEY = \"host_hostname\""
   },
   { "name": "testdatabase", "label": "TestDataBase", "query": "influxdb" }
  ]
 },
 "panels": [
  { "title": "$hostname", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "hostname" },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_monitor",
     "query": "SELECT \"mem\" FROM \"process_monitor\"  WHERE \"hostname\" = '${hostname:text}'  AND \"host_hostname\" = '${host_hostname:text}'  AND $timeFilter GROUP BY \"process\" ",
     "select": [
      [
       { "params": [ "mem" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "process", "operator": "=", "value": "ncs" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"mem_pkg\" FROM \"process_monitor\"  WHERE \"hostname\" = '${hostname:text}' AND \"host_hostname\" = '${host_hostname:text}'   AND $timeFilter GROUP BY \"process\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_monitor",
     "query": "SELECT \"cpu\" FROM \"process_monitor\"  WHERE \"hostname\" = '${hostname:text}' AND \"host_hostname\" = '${host_hostname:text}'    AND $timeFilter GROUP BY \"process\" ",
     "select": [
      [
       { "params": [ "mem" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "process", "operator": "=", "value": "ncs" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"cpu_pkg\" FROM \"process_monitor\"  WHERE \"hostname\" = '${hostname:text}' AND \"host_hostname\" = '${host_hostname:text}'   AND $timeFilter GROUP BY \"process\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "process_monitor",
     "query": "SELECT \"conn\" FROM \"process_monitor\"  WHERE \"hostname\" = '${hostname:text}' AND \"host_hostname\" = '${host_hostname:text}'    AND $timeFilter GROUP BY \"process\" ",
     "select": [
      [
       { "params": [ "mem" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "process", "operator": "=", "value": "ncs" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT \"conn_pkg\" FROM \"process_monitor\"  WHERE \"hostname\" = '${hostname:text}' AND \"host_hostname\" = '${host_hostname:text}'   AND $timeFilter GROUP BY \"process\" ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}